#!/usr/bin/env python3
"""
🔧 Setup Telephony - Configuration interactive

Configure facilement votre connexion téléphonique!

Usage:
    python setup_telephony.py
"""

import os
import subprocess
import sys
from pathlib import Path


def print_header():
    print()
    print("=" * 60)
    print("📞 Open Medical Secretary - Configuration Téléphonie")
    print("=" * 60)
    print()


def print_providers():
    print("Choisissez votre opérateur SIP:\n")
    print("  1. OVH Télécom (recommandé pour la France)")
    print("  2. Twilio (international)")
    print("  3. Free SIP (Freebox)")
    print("  4. Autre opérateur SIP")
    print()


def get_ovh_config():
    """Get OVH SIP configuration."""
    print("\n📋 Configuration OVH Télécom")
    print("-" * 40)
    print("Connectez-vous à: https://www.ovhtelecom.fr/manager/")
    print("Allez dans: Téléphonie > Votre ligne > Configuration SIP\n")
    
    username = input("Identifiant SIP (ex: 0033XXXXXXXXX): ").strip()
    password = input("Mot de passe SIP: ").strip()
    
    return {
        "SIP_SERVER": "siptrunk.ovh.net",
        "SIP_PORT": "5060",
        "SIP_USERNAME": username,
        "SIP_PASSWORD": password,
    }


def get_twilio_config():
    """Get Twilio SIP configuration."""
    print("\n📋 Configuration Twilio")
    print("-" * 40)
    print("Connectez-vous à: https://console.twilio.com/")
    print("Allez dans: Elastic SIP Trunking > Trunks\n")
    
    print("Créez un trunk et notez:")
    print("  - Termination SIP URI")
    print("  - Credential (username/password)\n")
    
    server = input("Serveur SIP (ex: xxxxx.pstn.twilio.com): ").strip()
    username = input("Username: ").strip()
    password = input("Password: ").strip()
    
    return {
        "SIP_SERVER": server,
        "SIP_PORT": "5060",
        "SIP_USERNAME": username,
        "SIP_PASSWORD": password,
    }


def get_free_config():
    """Get Free SIP configuration."""
    print("\n📋 Configuration Free SIP (Freebox)")
    print("-" * 40)
    print("Connectez-vous à: https://subscribe.free.fr/login/")
    print("Allez dans: Téléphonie > Gestion SIP\n")
    
    username = input("Identifiant SIP: ").strip()
    password = input("Mot de passe SIP: ").strip()
    
    return {
        "SIP_SERVER": "freephonie.net",
        "SIP_PORT": "5060",
        "SIP_USERNAME": username,
        "SIP_PASSWORD": password,
    }


def get_custom_config():
    """Get custom SIP configuration."""
    print("\n📋 Configuration SIP personnalisée")
    print("-" * 40)
    
    server = input("Serveur SIP: ").strip()
    port = input("Port SIP [5060]: ").strip() or "5060"
    username = input("Identifiant SIP: ").strip()
    password = input("Mot de passe SIP: ").strip()
    
    return {
        "SIP_SERVER": server,
        "SIP_PORT": port,
        "SIP_USERNAME": username,
        "SIP_PASSWORD": password,
    }


def save_env_file(config: dict):
    """Save configuration to .env file."""
    env_path = Path(__file__).parent / ".env"
    
    # Read existing .env if exists
    existing = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, value = line.strip().split("=", 1)
                    existing[key] = value
    
    # Update with new config
    existing.update(config)
    
    # Write back
    with open(env_path, "w") as f:
        f.write("# Open Medical Secretary - Configuration\n")
        f.write("# Generated by setup_telephony.py\n\n")
        f.write("# SIP Trunk Configuration\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")
    
    print(f"\n✅ Configuration sauvegardée dans: {env_path}")


def test_connection(config: dict):
    """Test SIP connection."""
    print("\n🔍 Test de connexion SIP...")
    print(f"   Serveur: {config['SIP_SERVER']}:{config['SIP_PORT']}")
    print(f"   Username: {config['SIP_USERNAME']}")
    
    # Simple DNS/port check
    import socket
    try:
        socket.setdefaulttimeout(5)
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex((config['SIP_SERVER'], int(config['SIP_PORT'])))
        sock.close()
        
        if result == 0:
            print("   ✅ Serveur accessible!")
        else:
            print("   ⚠️ Serveur non accessible (normal si UDP uniquement)")
    except Exception as e:
        print(f"   ⚠️ Erreur: {e}")


def print_next_steps():
    """Print next steps."""
    print("\n" + "=" * 60)
    print("📋 Prochaines étapes")
    print("=" * 60)
    print("""
1. Lancez Asterisk avec Docker:
   docker-compose up -d asterisk

2. Lancez l'assistant vocal:
   python dashboard.py

3. Testez avec un appel entrant sur votre numéro!

📞 Configuration Asterisk:
   - Les appels entrants sont automatiquement routés vers l'IA
   - Extension 100 pour tests internes

🔍 Logs Asterisk:
   docker logs -f open-med-asterisk
""")


def main():
    print_header()
    print_providers()
    
    choice = input("Votre choix [1-4]: ").strip()
    
    if choice == "1":
        config = get_ovh_config()
    elif choice == "2":
        config = get_twilio_config()
    elif choice == "3":
        config = get_free_config()
    elif choice == "4":
        config = get_custom_config()
    else:
        print("❌ Choix invalide")
        return
    
    # Save configuration
    save_env_file(config)
    
    # Test connection
    test_connection(config)
    
    # Print next steps
    print_next_steps()


if __name__ == "__main__":
    main()
